version: '3.8'

services:
  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:80"
      - "3443:443"
    environment:
      - VITE_API_BASE_URL=http://whyland-ai.nakedsun.xyz:8000
      - VITE_WS_URL=ws://whyland-ai.nakedsun.xyz:8000/ws
      - VITE_APP_NAME=Agentic Frontend
      - VITE_APP_VERSION=0.1.0
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
